version: "3"
services:
  sdc_db:
    build: data/
  sdc_service:
    build: server/
    depends_on:
      - 'adidas_related_info'
    ports:
      - '3001:3001'
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    volumes:
      - adidas_related_info:/var/lib/postgresql/data

